"""Core placeholder data structures for the R&D Agent scaffold."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class TaskSpec:
    """Normalized task description and constraints."""

    task_id: str
    description: str
    constraints: Dict[str, str] = field(default_factory=dict)


@dataclass
class DataSplitManifest:
    """Fixed train/val/test split indices for deterministic evaluation."""

    train_ids: List[str] = field(default_factory=list)
    val_ids: List[str] = field(default_factory=list)
    test_ids: List[str] = field(default_factory=list)
    seed: int = 0


@dataclass
class DataSummaryReport:
    """Dataset summary statistics and schema notes."""

    row_count: int = 0
    field_types: Dict[str, str] = field(default_factory=dict)
    missing_rates: Dict[str, float] = field(default_factory=dict)


@dataclass
class TaskArtifacts:
    """Artifacts produced by the task intake and data splitter module."""

    task_spec: TaskSpec
    split_manifest: DataSplitManifest
    summary_report: DataSummaryReport


@dataclass
class ExplorationGraph:
    """Exploration graph for tracking proposals, artifacts, and scores."""

    nodes: List["NodeRecord"] = field(default_factory=list)
    edges: List["GraphEdge"] = field(default_factory=list)


@dataclass
class GraphEdge:
    """Directed edge between two exploration nodes."""

    parent_id: str
    child_id: str


@dataclass
class NodeRecord:
    """Metadata for a single node in the exploration graph."""

    node_id: str
    parent_ids: List[str] = field(default_factory=list)
    proposal_id: Optional[str] = None
    artifact_id: Optional[str] = None
    score_id: Optional[str] = None


@dataclass
class Plan:
    """Plan for allocating exploration and exploitation within a loop."""

    plan_id: str
    exploration_strength: float = 0.0
    budget_allocation: Dict[str, float] = field(default_factory=dict)
    guidance: List[str] = field(default_factory=list)


@dataclass
class Proposal:
    """Structured proposal produced by the reasoning service."""

    proposal_id: str
    summary: str
    constraints: List[str] = field(default_factory=list)
    virtual_score: float = 0.0


@dataclass
class CodeArtifact:
    """Runnable code artifact generated by the development service."""

    artifact_id: str
    description: str
    location: str


@dataclass
class Score:
    """Evaluation score with metric metadata."""

    score_id: str
    value: float
    metric_name: str
    details: Dict[str, str] = field(default_factory=dict)


@dataclass
class LoopState:
    """State for the R&D loop execution."""

    loop_id: str
    iteration: int = 0
    status: str = "initialized"


@dataclass
class LoopContext:
    """Bundled context for loop state and budget tracking."""

    loop_state: LoopState
    budget: "BudgetLedger"


@dataclass
class BudgetLedger:
    """Tracks time and resource usage for the loop."""

    total_time_budget: float
    elapsed_time: float = 0.0


@dataclass
class PlanningContext:
    """Input context for plan generation."""

    loop_state: LoopState
    budget: BudgetLedger
    history_summary: Dict[str, str] = field(default_factory=dict)


@dataclass
class ContextPack:
    """Context bundle from memory service for reasoning."""

    items: List[str] = field(default_factory=list)
    highlights: List[str] = field(default_factory=list)


@dataclass
class ExecutionResult:
    """Execution output and runtime metadata."""

    run_id: str
    exit_code: int
    logs_ref: str
    artifacts_ref: str


@dataclass
class EvalResult:
    """Evaluation result with score reference."""

    score: Score
    report_ref: str


@dataclass
class PhaseResultMeta:
    """Minimal metadata for a completed loop phase."""

    proposal_id: Optional[str] = None
    artifact_id: Optional[str] = None
    score_id: Optional[str] = None
    notes: str = ""
