"""Quant scenario LLM prompt templates for alpha factor mining."""

from __future__ import annotations

DATA_SCHEMA_DESCRIPTION: str = (
    "Input DataFrame columns:\n"
    "  - date: datetime, trading date\n"
    "  - stock_id: str, stock identifier (e.g. 'STOCK_001')\n"
    "  - open: float, opening price\n"
    "  - high: float, intraday high price\n"
    "  - low: float, intraday low price\n"
    "  - close: float, closing price\n"
    "  - volume: float, trading volume\n"
    "\n"
    "Output DataFrame must contain exactly: date, stock_id, factor_value (float)."
)

FACTOR_PROPOSAL_SYSTEM_PROMPT: str = (
    "You are a quantitative researcher proposing alpha factors for stock return prediction.\n"
    "\n"
    "A good alpha factor:\n"
    "  1. Predicts future returns based on past price/volume data only.\n"
    "  2. Is NOT forward-looking (no look-ahead bias).\n"
    "  3. Has an economic or behavioral rationale.\n"
    "  4. Generalizes across stocks and time periods.\n"
    "\n"
    "Propose a factor hypothesis in the following format:\n"
    "  Name: <short name>\n"
    "  Hypothesis: <what pattern you expect and why>\n"
    "  Formulation: <mathematical formula or algorithmic description>\n"
    "  Expected behavior: <when should this factor score high vs low>\n"
    "\n"
    "Be specific and concrete. Avoid vague concepts.\n"
    "Only use: date, stock_id, open, high, low, close, volume."
)

FACTOR_PROPOSAL_USER_TEMPLATE: str = (
    "Research task: {task_summary}\n"
    "\n"
    "Previously tried factors and performance:\n"
    "{previous_factors}\n"
    "\n"
    "Feedback from last iteration:\n"
    "{feedback}\n"
    "\n"
    "Propose a NEW alpha factor that addresses the feedback above."
)

FACTOR_CODE_SYSTEM_PROMPT: str = (
    "You are a quantitative developer implementing alpha factors in Python.\n"
    "\n"
    "You will receive a factor hypothesis and implement it as Python code.\n"
    "\n"
    "REQUIRED function signature:\n"
    "  def compute_factor(df: pd.DataFrame) -> pd.DataFrame:\n"
    "\n"
    "Input:\n" + DATA_SCHEMA_DESCRIPTION + "\n"
    "\n"
    "Output:\n"
    "  DataFrame with exactly three columns: date, stock_id, factor_value\n"
    "  factor_value must be float, may contain NaN for missing data.\n"
    "\n"
    "STRICT RULES:\n"
    "  - Import only: numpy (as np), pandas (as pd), math, statistics\n"
    "  - NO os, subprocess, requests, sys, or file I/O\n"
    "  - NO future data: only use df rows with date <= current date\n"
    "  - Use groupby('stock_id') for cross-sectional operations\n"
    "  - Handle NaN: use .fillna(), .dropna(), or pd.isna() guards\n"
    "  - The function must be callable directly, no class wrappers\n"
    "  - Keep the implementation concise: under 40 lines, no comments, no explanatory prose\n"
    "\n"
    "COMMON MISTAKES TO AVOID:\n"
    "  - Using .shift(-n) (negative shift = future data = lookahead bias)\n"
    "  - Forgetting to handle the first N rows when using rolling/pct_change\n"
    "  - Returning a DataFrame without exactly [date, stock_id, factor_value]\n"
    "  - Using global variables or mutable state\n"
    "\n"
    "SELF-CHECK before returning:\n"
    "  1. Does the output have exactly 3 columns: date, stock_id, factor_value?\n"
    "  2. Is factor_value numeric (float)?\n"
    "  3. Are there no NaN-only results?\n"
)

FACTOR_CODE_USER_TEMPLATE: str = (
    "Factor hypothesis:\n"
    "{factor_hypothesis}\n"
    "\n"
    "Data schema:\n"
    "{data_schema}\n"
    "\n"
    "Reference patterns:\n"
    "- Momentum uses `groupby('stock_id')['close'].pct_change(5)`.\n"
    "- Volatility uses `groupby('stock_id')['close'].pct_change().rolling(20).std()`.\n"
    "\n"
    "RULES:\n"
    "- Return only one fenced python code block.\n"
    "- No JSON wrapper.\n"
    "- The code block must define `compute_factor(df)` returning a DataFrame "
    "with [date, stock_id, factor_value].\n"
    "- Keep the code concise and complete."
)

FEEDBACK_ANALYSIS_TEMPLATE: str = (
    "Analyze the following factor backtest results and suggest improvements.\n"
    "\n"
    "Factor code:\n"
    "{factor_code}\n"
    "\n"
    "Metrics (test period):\n"
    "  Sharpe:  {sharpe:.4f}  (target: > 0.5)\n"
    "  IC:      {ic:.4f}      (target: > 0.02)\n"
    "  ICIR:    {icir:.4f}    (target: > 0.3)\n"
    "  MDD:     {mdd:.4f}     (target: > -0.35)\n"
    "\n"
    "Execution logs:\n"
    "{execution_logs}\n"
    "\n"
    "Metric definitions:\n"
    "  Sharpe: risk-adjusted return (higher is better)\n"
    "  IC: correlation between factor and next-day return (closer to ±1 is better)\n"
    "  ICIR: consistency of IC over time (higher means more stable alpha)\n"
    "  MDD: worst peak-to-trough drawdown (closer to 0 is better)\n"
    "\n"
    "Provide:\n"
    "  1. Root cause of underperformance (if any)\n"
    "  2. Specific modification to the factor formula\n"
    "  3. Expected impact on each metric\n"
)

FACTOR_CODE_EXAMPLE: str = (
    "import pandas as pd\n"
    "import numpy as np\n"
    "\n"
    "\n"
    "def compute_factor(df: pd.DataFrame) -> pd.DataFrame:\n"
    "    result = df[['date', 'stock_id']].copy()\n"
    "    result['factor_value'] = df.groupby('stock_id')['close'].pct_change(5)\n"
    "    return result[['date', 'stock_id', 'factor_value']]\n"
)
